"""Type stubs for the bookreplay extension module."""

from __future__ import annotations

from typing import Sequence

NO_OCO_GROUP: int
ANY_INSTRUMENT: int
NEVER_NS: int

class BookreplayError(Exception): ...
class DbnError(BookreplayError): ...
class ReplayError(BookreplayError): ...

class Side:
    BID: Side
    ASK: Side
    NONE: Side

class OrderType:
    MARKET: OrderType
    LIMIT: OrderType
    STOP: OrderType
    STOP_LIMIT: OrderType

class LatencyClass:
    ORDER_ENTRY: LatencyClass
    PROTECTION_ARM: LatencyClass

class OrderStatus:
    PENDING: OrderStatus
    LIVE: OrderStatus
    ELECTED: OrderStatus
    FILLED: OrderStatus
    CANCELLED: OrderStatus
    OCO_CANCELLED: OrderStatus
    REJECTED: OrderStatus

class FillReason:
    MARKET: FillReason
    LIMIT_THROUGH: FillReason
    STOP_ELECTED: FillReason
    STOP_LIMIT_THROUGH: FillReason

class NoAggressorPolicy:
    NEITHER_SIDE: NoAggressorPolicy
    BOTH_SIDES: NoAggressorPolicy

class FillSizePolicy:
    PRINT_CAPPED: FillSizePolicy
    FULL_REMAINING: FillSizePolicy

class Latency:
    def __init__(
        self, *, order_entry_ns: int, protection_arm_ns: int, cancel_ns: int
    ) -> None: ...
    @property
    def order_entry_ns(self) -> int: ...
    @property
    def protection_arm_ns(self) -> int: ...
    @property
    def cancel_ns(self) -> int: ...

class TickScale:
    def __init__(self, tick_size: int) -> None: ...
    @property
    def tick_size(self) -> int: ...
    def to_price(self, ticks: int) -> int: ...
    def to_ticks(self, price: int) -> int: ...

class Order:
    id: int
    type: OrderType
    side: Side
    qty: int
    trigger_ticks: int
    limit_ticks: int
    live_from_ns: int
    oco_group: int
    latency: LatencyClass
    def __init__(
        self,
        *,
        id: int,
        type: OrderType,
        side: Side,
        qty: int,
        live_from_ns: int,
        trigger_ticks: int = ...,
        limit_ticks: int = ...,
        oco_group: int = ...,
        latency: LatencyClass = ...,
    ) -> None: ...

class Fill:
    @property
    def seq(self) -> int: ...
    @property
    def order_id(self) -> int: ...
    @property
    def oco_group(self) -> int: ...
    @property
    def ts_ns(self) -> int: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def price(self) -> int: ...
    @property
    def price_ticks(self) -> int: ...
    @property
    def qty(self) -> int: ...
    @property
    def remaining(self) -> int: ...
    @property
    def print_size(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def side(self) -> Side: ...
    @property
    def aggressor(self) -> Side: ...
    @property
    def reason(self) -> FillReason: ...

class Tick:
    def __init__(
        self,
        *,
        ts: int,
        price: int,
        size: int,
        aggressor: Side,
        ts_event: int = ...,
        instrument_id: int = ...,
        sequence: int = ...,
    ) -> None: ...
    @property
    def ts(self) -> int: ...
    @property
    def ts_event(self) -> int: ...
    @property
    def price(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def instrument_id(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    @property
    def aggressor(self) -> Side: ...

class OrderView:
    @property
    def status(self) -> OrderStatus: ...
    @property
    def type(self) -> OrderType: ...
    @property
    def side(self) -> Side: ...
    @property
    def oco_group(self) -> int: ...
    @property
    def qty(self) -> int: ...
    @property
    def remaining(self) -> int: ...
    @property
    def filled(self) -> int: ...
    @property
    def oco_reduced(self) -> int: ...
    @property
    def effective_live_ns(self) -> int: ...
    @property
    def effective_cancel_ns(self) -> int: ...
    @property
    def elected_ns(self) -> int: ...
    @property
    def trigger_price(self) -> int: ...
    @property
    def limit_price(self) -> int: ...

class TradeSourceStats:
    @property
    def records(self) -> int: ...
    @property
    def ticks(self) -> int: ...
    @property
    def skipped_non_trade(self) -> int: ...
    @property
    def skipped_other_instrument(self) -> int: ...
    @property
    def undef_price(self) -> int: ...
    @property
    def zero_size(self) -> int: ...
    @property
    def bad_ts_recv(self) -> int: ...
    @property
    def no_aggressor(self) -> int: ...
    @property
    def reconciles(self) -> bool: ...

class ReplayStats:
    @property
    def ticks(self) -> int: ...
    @property
    def no_aggressor_ticks(self) -> int: ...
    @property
    def no_aggressor_passive_skips(self) -> int: ...
    @property
    def tick_charged_qty(self) -> int: ...
    @property
    def elections(self) -> int: ...
    @property
    def stop_entry_rejects(self) -> int: ...
    @property
    def fills(self) -> int: ...
    @property
    def partial_fills(self) -> int: ...
    @property
    def oco_reductions(self) -> int: ...
    @property
    def oco_cancels(self) -> int: ...
    @property
    def cancels_applied(self) -> int: ...
    @property
    def late_arm_orders(self) -> int: ...
    @property
    def late_arm_ns_total(self) -> int: ...
    @property
    def reallocations(self) -> int: ...

class ReplayConfig:
    no_aggressor: NoAggressorPolicy
    fill_size: FillSizePolicy
    reserve_live_orders: int
    reserve_fills_per_advance: int
    @property
    def latency(self) -> Latency: ...
    @property
    def scale(self) -> TickScale: ...
    def __init__(
        self,
        *,
        latency: Latency,
        scale: TickScale,
        no_aggressor: NoAggressorPolicy = ...,
        fill_size: FillSizePolicy = ...,
        reserve_live_orders: int = ...,
        reserve_fills_per_advance: int = ...,
    ) -> None: ...

class TickBuffer:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Tick: ...
    @property
    def stats(self) -> TradeSourceStats: ...

class NakedWindowQuery:
    entry_fill_ts: int
    window_ns: int
    entry_price: int
    stop_price: int
    position_side: Side
    def __init__(
        self,
        *,
        entry_fill_ts: int,
        window_ns: int,
        entry_price: int,
        stop_price: int,
        position_side: Side,
    ) -> None: ...

class NakedWindowResult:
    @property
    def ticks(self) -> int: ...
    @property
    def no_aggressor_ticks(self) -> int: ...
    @property
    def volume(self) -> int: ...
    @property
    def stop_reached(self) -> bool: ...
    @property
    def first_reach_ts(self) -> int: ...
    @property
    def worst_price(self) -> int: ...
    @property
    def mae_ticks(self) -> int: ...
    @property
    def window_end_ns(self) -> int: ...

class Replay:
    def __init__(self, ticks: TickBuffer, config: ReplayConfig) -> None: ...
    @staticmethod
    def open_dbn(path: str, config: ReplayConfig, *, instrument_id: int) -> Replay: ...
    def submit(self, order: Order) -> None: ...
    def cancel(self, id: int) -> None: ...
    def cancel_at(self, id: int, request_ts_ns: int) -> None: ...
    def advance_to(self, ts_ns: int) -> list[Fill]: ...
    def order(self, id: int) -> OrderView: ...
    @property
    def now_ns(self) -> int: ...
    @property
    def exhausted(self) -> bool: ...
    @property
    def stats(self) -> ReplayStats: ...
    @property
    def source_stats(self) -> TradeSourceStats: ...

def load_ticks(path: str, *, instrument_id: int) -> TickBuffer: ...
def ticks_from(ticks: Sequence[Tick]) -> TickBuffer: ...
def naked_window_scan(
    ticks: TickBuffer,
    queries: Sequence[NakedWindowQuery],
    scale: TickScale,
    *,
    max_concurrent: int = ...,
) -> list[NakedWindowResult]: ...
